# Jumpsuit
- type: loadout
  id: JumpsuitHoSBlueHarmony
  equipment: 
    jumpsuit: ClothingUniformJumpsuitHoSBlue

- type: loadout
  id: JumpsuitHoSTurtleNeckHarmony
  equipment: 
    jumpsuit: ClothingUniformJumpsuitHeadOfSecurityTurtleneckHarmony

- type: loadout
  id: JumpskirtHoSTurtleNeckHarmony
  equipment: 
    jumpsuit: ClothingUniformJumpskirtHeadOfSecurityTurtleneckHarmony

- type: loadout
  id: JumpsuitHoSGrey
  equipment: 
    jumpsuit: ClothingUniformJumpsuitHoSGrey

# Head
- type: loadout
  id: HoSWidebrimHarmony
  equipment:
    head: ClothingHeadHatHoSWidebrimHarmony

- type: loadout
  id: HoSSoftHarmony
  equipment:
    head: ClothingHeadHatHoSSoftHarmony